/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedStampsRouteImport } from './routes/_authenticated/stamps'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedInventoryRouteImport } from './routes/_authenticated/inventory'
import { Route as AuthenticatedEventsRouteImport } from './routes/_authenticated/events'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedBatchesRouteImport } from './routes/_authenticated/batches'
import { Route as AuthenticatedActivityRouteImport } from './routes/_authenticated/activity'
import { Route as AuthenticatedStampsNewRouteImport } from './routes/_authenticated/stamps_.new'
import { Route as AuthenticatedStampsIdRouteImport } from './routes/_authenticated/stamps_.$id'
import { Route as AuthenticatedSettingsUsersRouteImport } from './routes/_authenticated/settings.users'
import { Route as AuthenticatedInventoryNewRouteImport } from './routes/_authenticated/inventory_.new'
import { Route as AuthenticatedInventoryIdRouteImport } from './routes/_authenticated/inventory_.$id'
import { Route as AuthenticatedEventsNewRouteImport } from './routes/_authenticated/events_.new'
import { Route as AuthenticatedEventsIdRouteImport } from './routes/_authenticated/events_.$id'
import { Route as AuthenticatedBatchesNewRouteImport } from './routes/_authenticated/batches_.new'
import { Route as AuthenticatedBatchesIdRouteImport } from './routes/_authenticated/batches_.$id'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedStampsRoute = AuthenticatedStampsRouteImport.update({
  id: '/stamps',
  path: '/stamps',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInventoryRoute = AuthenticatedInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEventsRoute = AuthenticatedEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBatchesRoute = AuthenticatedBatchesRouteImport.update({
  id: '/batches',
  path: '/batches',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedActivityRoute = AuthenticatedActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStampsNewRoute = AuthenticatedStampsNewRouteImport.update({
  id: '/stamps_/new',
  path: '/stamps/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStampsIdRoute = AuthenticatedStampsIdRouteImport.update({
  id: '/stamps_/$id',
  path: '/stamps/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsUsersRoute =
  AuthenticatedSettingsUsersRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedInventoryNewRoute =
  AuthenticatedInventoryNewRouteImport.update({
    id: '/inventory_/new',
    path: '/inventory/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInventoryIdRoute =
  AuthenticatedInventoryIdRouteImport.update({
    id: '/inventory_/$id',
    path: '/inventory/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEventsNewRoute = AuthenticatedEventsNewRouteImport.update({
  id: '/events_/new',
  path: '/events/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEventsIdRoute = AuthenticatedEventsIdRouteImport.update({
  id: '/events_/$id',
  path: '/events/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBatchesNewRoute = AuthenticatedBatchesNewRouteImport.update({
  id: '/batches_/new',
  path: '/batches/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBatchesIdRoute = AuthenticatedBatchesIdRouteImport.update({
  id: '/batches_/$id',
  path: '/batches/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/activity': typeof AuthenticatedActivityRoute
  '/batches': typeof AuthenticatedBatchesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/events': typeof AuthenticatedEventsRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/stamps': typeof AuthenticatedStampsRoute
  '/batches/$id': typeof AuthenticatedBatchesIdRoute
  '/batches/new': typeof AuthenticatedBatchesNewRoute
  '/events/$id': typeof AuthenticatedEventsIdRoute
  '/events/new': typeof AuthenticatedEventsNewRoute
  '/inventory/$id': typeof AuthenticatedInventoryIdRoute
  '/inventory/new': typeof AuthenticatedInventoryNewRoute
  '/settings/users': typeof AuthenticatedSettingsUsersRoute
  '/stamps/$id': typeof AuthenticatedStampsIdRoute
  '/stamps/new': typeof AuthenticatedStampsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/activity': typeof AuthenticatedActivityRoute
  '/batches': typeof AuthenticatedBatchesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/events': typeof AuthenticatedEventsRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/stamps': typeof AuthenticatedStampsRoute
  '/batches/$id': typeof AuthenticatedBatchesIdRoute
  '/batches/new': typeof AuthenticatedBatchesNewRoute
  '/events/$id': typeof AuthenticatedEventsIdRoute
  '/events/new': typeof AuthenticatedEventsNewRoute
  '/inventory/$id': typeof AuthenticatedInventoryIdRoute
  '/inventory/new': typeof AuthenticatedInventoryNewRoute
  '/settings/users': typeof AuthenticatedSettingsUsersRoute
  '/stamps/$id': typeof AuthenticatedStampsIdRoute
  '/stamps/new': typeof AuthenticatedStampsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/activity': typeof AuthenticatedActivityRoute
  '/_authenticated/batches': typeof AuthenticatedBatchesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/events': typeof AuthenticatedEventsRoute
  '/_authenticated/inventory': typeof AuthenticatedInventoryRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/_authenticated/stamps': typeof AuthenticatedStampsRoute
  '/_authenticated/batches_/$id': typeof AuthenticatedBatchesIdRoute
  '/_authenticated/batches_/new': typeof AuthenticatedBatchesNewRoute
  '/_authenticated/events_/$id': typeof AuthenticatedEventsIdRoute
  '/_authenticated/events_/new': typeof AuthenticatedEventsNewRoute
  '/_authenticated/inventory_/$id': typeof AuthenticatedInventoryIdRoute
  '/_authenticated/inventory_/new': typeof AuthenticatedInventoryNewRoute
  '/_authenticated/settings/users': typeof AuthenticatedSettingsUsersRoute
  '/_authenticated/stamps_/$id': typeof AuthenticatedStampsIdRoute
  '/_authenticated/stamps_/new': typeof AuthenticatedStampsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/activity'
    | '/batches'
    | '/dashboard'
    | '/events'
    | '/inventory'
    | '/settings'
    | '/stamps'
    | '/batches/$id'
    | '/batches/new'
    | '/events/$id'
    | '/events/new'
    | '/inventory/$id'
    | '/inventory/new'
    | '/settings/users'
    | '/stamps/$id'
    | '/stamps/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/activity'
    | '/batches'
    | '/dashboard'
    | '/events'
    | '/inventory'
    | '/settings'
    | '/stamps'
    | '/batches/$id'
    | '/batches/new'
    | '/events/$id'
    | '/events/new'
    | '/inventory/$id'
    | '/inventory/new'
    | '/settings/users'
    | '/stamps/$id'
    | '/stamps/new'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/activity'
    | '/_authenticated/batches'
    | '/_authenticated/dashboard'
    | '/_authenticated/events'
    | '/_authenticated/inventory'
    | '/_authenticated/settings'
    | '/_authenticated/stamps'
    | '/_authenticated/batches_/$id'
    | '/_authenticated/batches_/new'
    | '/_authenticated/events_/$id'
    | '/_authenticated/events_/new'
    | '/_authenticated/inventory_/$id'
    | '/_authenticated/inventory_/new'
    | '/_authenticated/settings/users'
    | '/_authenticated/stamps_/$id'
    | '/_authenticated/stamps_/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/stamps': {
      id: '/_authenticated/stamps'
      path: '/stamps'
      fullPath: '/stamps'
      preLoaderRoute: typeof AuthenticatedStampsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventory': {
      id: '/_authenticated/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AuthenticatedInventoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/events': {
      id: '/_authenticated/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof AuthenticatedEventsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/batches': {
      id: '/_authenticated/batches'
      path: '/batches'
      fullPath: '/batches'
      preLoaderRoute: typeof AuthenticatedBatchesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/activity': {
      id: '/_authenticated/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AuthenticatedActivityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/stamps_/new': {
      id: '/_authenticated/stamps_/new'
      path: '/stamps/new'
      fullPath: '/stamps/new'
      preLoaderRoute: typeof AuthenticatedStampsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/stamps_/$id': {
      id: '/_authenticated/stamps_/$id'
      path: '/stamps/$id'
      fullPath: '/stamps/$id'
      preLoaderRoute: typeof AuthenticatedStampsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/users': {
      id: '/_authenticated/settings/users'
      path: '/users'
      fullPath: '/settings/users'
      preLoaderRoute: typeof AuthenticatedSettingsUsersRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/inventory_/new': {
      id: '/_authenticated/inventory_/new'
      path: '/inventory/new'
      fullPath: '/inventory/new'
      preLoaderRoute: typeof AuthenticatedInventoryNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventory_/$id': {
      id: '/_authenticated/inventory_/$id'
      path: '/inventory/$id'
      fullPath: '/inventory/$id'
      preLoaderRoute: typeof AuthenticatedInventoryIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/events_/new': {
      id: '/_authenticated/events_/new'
      path: '/events/new'
      fullPath: '/events/new'
      preLoaderRoute: typeof AuthenticatedEventsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/events_/$id': {
      id: '/_authenticated/events_/$id'
      path: '/events/$id'
      fullPath: '/events/$id'
      preLoaderRoute: typeof AuthenticatedEventsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/batches_/new': {
      id: '/_authenticated/batches_/new'
      path: '/batches/new'
      fullPath: '/batches/new'
      preLoaderRoute: typeof AuthenticatedBatchesNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/batches_/$id': {
      id: '/_authenticated/batches_/$id'
      path: '/batches/$id'
      fullPath: '/batches/$id'
      preLoaderRoute: typeof AuthenticatedBatchesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedSettingsRouteChildren {
  AuthenticatedSettingsUsersRoute: typeof AuthenticatedSettingsUsersRoute
}

const AuthenticatedSettingsRouteChildren: AuthenticatedSettingsRouteChildren = {
  AuthenticatedSettingsUsersRoute: AuthenticatedSettingsUsersRoute,
}

const AuthenticatedSettingsRouteWithChildren =
  AuthenticatedSettingsRoute._addFileChildren(
    AuthenticatedSettingsRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedActivityRoute: typeof AuthenticatedActivityRoute
  AuthenticatedBatchesRoute: typeof AuthenticatedBatchesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEventsRoute: typeof AuthenticatedEventsRoute
  AuthenticatedInventoryRoute: typeof AuthenticatedInventoryRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRouteWithChildren
  AuthenticatedStampsRoute: typeof AuthenticatedStampsRoute
  AuthenticatedBatchesIdRoute: typeof AuthenticatedBatchesIdRoute
  AuthenticatedBatchesNewRoute: typeof AuthenticatedBatchesNewRoute
  AuthenticatedEventsIdRoute: typeof AuthenticatedEventsIdRoute
  AuthenticatedEventsNewRoute: typeof AuthenticatedEventsNewRoute
  AuthenticatedInventoryIdRoute: typeof AuthenticatedInventoryIdRoute
  AuthenticatedInventoryNewRoute: typeof AuthenticatedInventoryNewRoute
  AuthenticatedStampsIdRoute: typeof AuthenticatedStampsIdRoute
  AuthenticatedStampsNewRoute: typeof AuthenticatedStampsNewRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedActivityRoute: AuthenticatedActivityRoute,
  AuthenticatedBatchesRoute: AuthenticatedBatchesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEventsRoute: AuthenticatedEventsRoute,
  AuthenticatedInventoryRoute: AuthenticatedInventoryRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRouteWithChildren,
  AuthenticatedStampsRoute: AuthenticatedStampsRoute,
  AuthenticatedBatchesIdRoute: AuthenticatedBatchesIdRoute,
  AuthenticatedBatchesNewRoute: AuthenticatedBatchesNewRoute,
  AuthenticatedEventsIdRoute: AuthenticatedEventsIdRoute,
  AuthenticatedEventsNewRoute: AuthenticatedEventsNewRoute,
  AuthenticatedInventoryIdRoute: AuthenticatedInventoryIdRoute,
  AuthenticatedInventoryNewRoute: AuthenticatedInventoryNewRoute,
  AuthenticatedStampsIdRoute: AuthenticatedStampsIdRoute,
  AuthenticatedStampsNewRoute: AuthenticatedStampsNewRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
